# Generated by Django 4.2.11 on 2025-10-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('english_url', models.URLField()),
                ('spanish_url', models.URLField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('bhakti_shastri', 'Bhakti Shastri'), ('bhakti_vaibhava', 'Bhakti Vaibhava'), ('bhakti_vedanta', 'Bhakti Vedanta'), ('bhakti_sarvabhauma', 'Bhakti Sarvabhauma')], max_length=20)),
                ('description_en', models.TextField()),
                ('description_es', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.TextField()),
                ('question_es', models.TextField()),
                ('answer_en', models.TextField()),
                ('answer_es', models.TextField()),
                ('verse_reference', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qas', to='study_app.book')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='study_app.course'),
        ),
    ]
