# Generated by Django 4.2.11 on 2025-10-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0003_qaupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('qa', 'Questions & Answers'), ('notes', 'Study Notes'), ('summary', 'Chapter Summary'), ('quiz', 'Quiz'), ('other', 'Other Material')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('both', 'Both Languages')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('english_file', models.FileField(blank=True, null=True, upload_to='study_materials/english/')),
                ('spanish_file', models.FileField(blank=True, null=True, upload_to='study_materials/spanish/')),
                ('bilingual_file', models.FileField(blank=True, null=True, upload_to='study_materials/bilingual/')),
                ('questions_json', models.JSONField(blank=True, null=True)),
                ('verse_reference', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='study_app.book')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
