# Generated by Django 4.2.25 on 2025-10-23 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_app', '0004_studymaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('chapters_range', models.CharField(help_text="e.g., 'Chapters 1-6' or 'Chapters 7-12'", max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_modules', to='study_app.course')),
            ],
            options={
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(help_text="e.g., 'Chapter 1' or 'Chapter 2'", max_length=10)),
                ('question_text', models.TextField()),
                ('correct_answers', models.TextField(help_text="Comma-separated list of acceptable answers based on Prabhupada's commentaries")),
                ('prabhupada_commentary', models.TextField(help_text='Relevant commentary from Srila Prabhupada')),
                ('additional_guidance', models.TextField(blank=True, help_text='Additional philosophical guidance')),
                ('verse_reference', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='study_app.book')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study_app.quizmodule')),
            ],
            options={
                'ordering': ['module', 'chapter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.book')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.quizmodule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
