# Generated by Django 4.2.25 on 2025-10-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0006_add_multiple_choice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answers',
            field=models.TextField(blank=True, help_text='Auto-populated: The correct answer will be stored here after students attempt the question', null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='prabhupada_commentary',
            field=models.TextField(blank=True, help_text='Auto-populated when students answer questions', null=True),
        ),
    ]
