# Generated by Django 4.2.25 on 2025-10-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0007_make_prabhupada_commentary_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='ai_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='feedback_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='is_siddhanta_aligned',
            field=models.BooleanField(default=False),
        ),
    ]
