# Generated by Django 4.2.25 on 2025-10-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0008_add_ai_validation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={},
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='additional_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='multiple_choice_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='prabhupada_commentary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
