# Generated by Django 4.2.25 on 2025-10-30 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0009_alter_quizquestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='book_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('text_extracted', models.BooleanField(default=False)),
                ('extracted_text', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='study_app.book')),
            ],
        ),
    ]
