#!/bin/bash
echo "🔧 FORCING DIRECT FIX"
echo "===================="

cd ~/django-vaishnava-study
source venv/bin/activate

# Step 1: Directly edit models.py to ensure unique_together is there
python3 << 'PYEOF'
import os

models_file = 'study_app/models.py'

# Read current content
with open(models_file, 'r') as f:
    content = f.read()

print("📝 Current models.py content around QuizQuestion Meta class:")

# Find and show the QuizQuestion Meta class
lines = content.split('\n')
quizquestion_start = -1
meta_start = -1

for i, line in enumerate(lines):
    if 'class QuizQuestion' in line:
        quizquestion_start = i
    if quizquestion_start != -1 and 'class Meta:' in line:
        meta_start = i
        break

if meta_start != -1:
    print(f"Found Meta class at line {meta_start + 1}")
    # Show 5 lines around Meta class
    start = max(0, meta_start - 2)
    end = min(len(lines), meta_start + 10)
    for j in range(start, end):
        print(f"{j+1}: {lines[j]}")
else:
    print("❌ Could not find QuizQuestion Meta class")

# Now force add unique_together
print("\n🔧 Forcing unique_together addition...")

# Method: Replace the entire Meta class section
new_lines = []
in_quizquestion = False
in_meta = False
meta_replaced = False

for i, line in enumerate(lines):
    if 'class QuizQuestion' in line:
        in_quizquestion = True
        new_lines.append(line)
    elif in_quizquestion and 'class Meta:' in line:
        in_meta = True
        new_lines.append(line)
        # Replace the entire Meta class with our version
        new_lines.append('        unique_together = [\'module\', \'verse_reference\', \'question_text\']')
        meta_replaced = True
    elif in_meta and line.strip() == '':
        in_meta = False
        in_quizquestion = False
        new_lines.append(line)
    elif not in_meta:
        new_lines.append(line)

if meta_replaced:
    with open(models_file, 'w') as f:
        f.write('\n'.join(new_lines))
    print("✅ Successfully replaced Meta class with unique_together")
else:
    print("❌ Could not replace Meta class")
PYEOF

# Step 2: Create migration using --verbosity 3 to see why it's not detecting changes
echo ""
echo "🔄 Creating migration with high verbosity..."
python manage.py makemigrations study_app --verbosity 3

# If still no migration, force create one
echo ""
echo "🔧 Checking if migration was created..."
if [ ! -f "study_app/migrations/0008_add_unique_constraint.py" ] && [ ! -f "study_app/migrations/0009_add_unique_constraint.py" ]; then
    echo "No migration created, forcing manual creation..."
    python3 << 'PYEOF'
import os

migration_dir = 'study_app/migrations'
# Find the latest migration
migrations = [f for f in os.listdir(migration_dir) if f.endswith('.py') and f != '__init__.py']
migrations.sort()
latest_migration = migrations[-1]
latest_number = latest_migration.split('_')[0]
next_number = str(int(latest_number) + 1).zfill(4)

migration_file = os.path.join(migration_dir, f'{next_number}_add_unique_constraint.py')

migration_content = f'''# Generated by Django
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '{latest_number}'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={{('module', 'verse_reference', 'question_text')}},
        ),
    ]
'''

with open(migration_file, 'w') as f:
    f.write(migration_content)

print(f"✅ Manually created migration: {migration_file}")
PYEOF
fi

# Step 3: Apply migration
echo ""
echo "🔄 Applying migration..."
python manage.py migrate study_app

# Step 4: Test the constraint using SQL directly
echo ""
echo "🧪 Testing constraint with SQL approach..."
python3 << 'PYEOF'
import sqlite3
import os

db_path = 'db.sqlite3'
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# First, let's check if the unique constraint exists in the database
cursor.execute("""
    SELECT name, sql FROM sqlite_master 
    WHERE type='index' AND tbl_name='study_app_quizquestion'
    AND sql LIKE '%UNIQUE%'
""")
unique_indexes = cursor.fetchall()

if unique_indexes:
    print("✅ Found unique indexes in database:")
    for idx in unique_indexes:
        print(f"   {idx[0]}: {idx[1]}")
else:
    print("❌ No unique indexes found in database")
    print("Creating unique constraint directly via SQL...")
    
    # Create the unique constraint directly
    cursor.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS unique_quiz_question 
        ON study_app_quizquestion(module_id, verse_reference, question_text)
    """)
    conn.commit()
    print("✅ Created unique constraint via direct SQL")

# Test the constraint
cursor.execute("SELECT module_id, verse_reference, question_text FROM study_app_quizquestion LIMIT 1")
test_row = cursor.fetchone()

if test_row:
    module_id, verse_ref, question_text = test_row
    print(f"Testing constraint with: module_id={module_id}, verse='{verse_ref}', question='{question_text[:30]}...'")
    
    try:
        cursor.execute("""
            INSERT INTO study_app_quizquestion 
            (module_id, verse_reference, question_text, chapter, book_id, "order", created_at)
            VALUES (?, ?, ?, 'Test', ?, 999, datetime('now'))
        """, (module_id, verse_ref, question_text, 1))
        conn.commit()
        print("❌ SQL UNIQUE CONSTRAINT FAILED")
        # Clean up
        cursor.execute("DELETE FROM study_app_quizquestion WHERE \"order\" = 999")
        conn.commit()
    except sqlite3.IntegrityError as e:
        print("✅ SQL UNIQUE CONSTRAINT WORKING!")
        print(f"   SQLite error: {e}")

conn.close()
PYEOF

echo ""
echo "🎯 DIRECT FIX COMPLETED!"
