# Generated by Django 4.2.25 on 2025-10-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0005_quizmodule_quizquestion_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='multiple_choice_options',
            field=models.TextField(blank=True, help_text="Pipe-separated options: 'Correct Answer|Wrong 1|Wrong 2|Wrong 3'", null=True),
        ),
    ]
