#!/bin/bash
echo "🔧 CREATING MANUAL MIGRATION"
echo "============================"

cd ~/django-vaishnava-study
source venv/bin/activate

# Step 1: Find the latest migration number
LATEST_MIG=$(python manage.py showmigrations study_app | grep "\[X\]" | tail -1 | awk -F'_' '{print $1}' | sed 's/^0*//')
if [ -z "$LATEST_MIG" ]; then
    LATEST_MIG=0
fi
NEXT_MIG=$((LATEST_MIG + 1))
MIGRATION_NAME=$(printf "%04d" $NEXT_MIG)_add_unique_constraint.py

echo "Next migration: $MIGRATION_NAME"

# Step 2: Create the migration file manually
python3 << PYEOF
import os

migration_dir = 'study_app/migrations'
migration_file = os.path.join(migration_dir, '$MIGRATION_NAME')

# Get the latest migration to set dependencies
import glob
migration_files = glob.glob(os.path.join(migration_dir, '*.py'))
migration_files.sort()
if migration_files:
    latest_migration = os.path.basename(migration_files[-1])
    dep_number = latest_migration.split('_')[0]
else:
    dep_number = '0001'

migration_content = '''# Generated by manual fix
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('study_app', '$dep_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('module', 'verse_reference', 'question_text')},
        ),
    ]
'''

with open(migration_file, 'w') as f:
    f.write(migration_content)

print(f"✅ Created migration: {migration_file}")
PYEOF

# Step 3: Apply the migration
echo ""
echo "🔄 Applying migration..."
python manage.py migrate study_app

# Step 4: Test the constraint
echo ""
echo "🧪 Testing constraint..."
python3 << 'PYEOF'
import os
import sys
import django

sys.path.append(os.getcwd())
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'website.settings')
django.setup()

from study_app.models import QuizQuestion
from django.db import IntegrityError

try:
    existing = QuizQuestion.objects.first()
    if existing:
        print("Creating duplicate to test constraint...")
        duplicate = QuizQuestion(
            book=existing.book,
            module=existing.module,
            chapter=existing.chapter,
            verse_reference=existing.verse_reference,
            question_text=existing.question_text,
            order=999
        )
        try:
            duplicate.save()
            print("❌ UNIQUE CONSTRAINT FAILED")
            duplicate.delete()
        except IntegrityError as e:
            print("✅ UNIQUE CONSTRAINT WORKING: IntegrityError raised")
            print(f"   Error: {e}")
        except Exception as e:
            print(f"⚠️  Other error: {e}")
    else:
        print("ℹ️  No questions to test with")
        
except Exception as e:
    print(f"❌ Test error: {e}")
PYEOF

echo ""
echo "🎉 MANUAL MIGRATION COMPLETED!"
